"""
AI-DAMS NLP classifier external validation.

The corpus-based test set (sqli_corpus.csv, evaluated in
train_nlp_classifier.py) scored 100% accuracy, which was flagged as a
likely overfitting artifact -- the corpus only has ~24 templates, and
train_test_split puts near-identical template skeletons on both sides
of the split. This script is the actual generalization check: it loads
the ALREADY-TRAINED model and tests it against external_validation.csv,
a hand-written set of payloads and benign queries that were NOT
generated by generate_sqli_corpus.py -- different phrasing, some
entirely different attack techniques (e.g. MSSQL command execution,
which isn't in any of the training corpus's 6 categories), and a
different application domain for the benign examples (blog/CMS rather
than e-commerce) to avoid any accidental vocabulary overlap.

Run train_nlp_classifier.py first -- this script depends on the
.joblib files it saves.
"""

import pandas as pd
import joblib
from sklearn.metrics import classification_report, confusion_matrix

MODEL_PATH = "nlp_classifier_model.joblib"
VECTORIZER_PATH = "nlp_classifier_vectorizer.joblib"
VALIDATION_PATH = "external_validation.csv"


def main():
    model = joblib.load(MODEL_PATH)
    vectorizer = joblib.load(VECTORIZER_PATH)

    df = pd.read_csv(VALIDATION_PATH)
    print(f"Loaded {len(df)} external validation examples: "
          f"{df['label'].sum()} malicious, {(df['label'] == 0).sum()} benign")
    print("None of these were generated by generate_sqli_corpus.py.\n")

    X = vectorizer.transform(df["query_text"])
    y_true = df["label"]
    y_pred = model.predict(X)

    print("--- Evaluation on genuinely novel, out-of-template examples ---")
    print(confusion_matrix(y_true, y_pred))
    print(classification_report(y_true, y_pred, target_names=["benign", "malicious"]))

    print("--- Every misclassified example (the actually useful diagnostic) ---")
    df["predicted"] = y_pred
    wrong = df[df["label"] != df["predicted"]]
    if len(wrong) == 0:
        print("None -- every external example was classified correctly.")
    else:
        for _, row in wrong.iterrows():
            true_label = "malicious" if row["label"] == 1 else "benign"
            pred_label = "malicious" if row["predicted"] == 1 else "benign"
            print(f"  TRUE={true_label:9s} PRED={pred_label:9s} | {row['query_text']!r} ({row['note']})")


if __name__ == "__main__":
    main()